### ISSUE TITLE
Thank you for your great work

### ISSUE THREAD

**Issue by Wanghq05** [Necolizer/ISTA-Net#1]
Do I want to know the difference between the clean and noise data sets of the SBU data set? Do they all need to be accurate? Again, you only have to run one data set.

**Comment by Necolizer** [comment]
Hi @Wanghq05 , the Clean version and the Noisy version are both available, with the latter having a longer valid frame length for each sample (about 12.3 frames longer). If you wanna evaluate on this dataset, maybe using both versions or just one of them are okay. Since this work is under review, my code and readme are now still updating, and there might be bugs in this version of code. Your diligence and passion for following the latest Action Recognition methods really surprise me :)

**Comment by Wanghq05** [comment]
Ha ha, you don't need to be surprised, we are the same teacher, and we are both Mr. Liu's students, I saw your code is a coincidence.

**Comment by Necolizer** [comment]
All right :)
